dataset:
  train:
    name: mixed
    prob_ls: [1.0]
    dataset_list:
    - name: hypersim_depth
      disp_name: hypersim_depth_train
      dir: hypersim_processed
      filenames: data_split/hypersim_depth/hypersim_train_filename_list.txt
      resize_to_hw:
      - 480
      - 640
   
