dataset:
  val:
  - name: hypersim_depth
    disp_name: hypersim_depth_train 
    dir: hypersim_processed_val
    filenames: data_split/hypersim_normals/hypersim_val_filename_list.txt
    resize_to_hw:
      - 480
      - 640

